services:
  backend:
    build:
      context: ./back/
      dockerfile: back.Dockerfile
    ports:
      - "5001:5001"
    networks:
      - default
  
  model:
    build:
      context: ./model/
      dockerfile: model.Dockerfile
    ports:
      - "5000:5000"
    networks:
      - default
  
  frontend:
    build:
      context: ./front/
      dockerfile: front.Dockerfile
    ports:
      - "5002:80"
    networks:
      - default
  
  monitoring:
    build:
      context: ./monitoring/
      dockerfile: prometheus.Dockerfile
    ports:
      - "9090:9090"
    networks:
      - default

networks:
  default:
    driver: host
